[[questions]]
question = "When was the known use of the word 'quiz'"
answer = "1781"
options = ["1781", "1771", "1871", "1881"]

[[questions]]
question = "What Language was this program built in"
asnwer = "Python"
options = ["Java", "C", "GoLang"]

[[questions]]
question = "When was Travis Born"
answer = "2002"
options = ["2003", "1999", "2000"]

[[questions]]
question = "How old is the White House"
answer = "39"
options = ["69", "92", "145"]

[[questions]]
question = "What's the official name of the := operator"
answer = "Assignment expression"
options = ["Named expression", "Walrus operator", "Colon equals operator"]

[[questions]]
question = "When does __name__ == '__main__' equal True in a Python file"
answer = "When the file is run as a script"
options = ["When the file is imported as a module", "When the file has a valid name",
    "When the file only has one function"]

[[questions]]
question = "Which version of Python is the first with TOML support built in"
answer = "3.11"
options = ["3.9", "3.10", "3.12"]
